name: MyMaid2
main: com.jaoafa.MyMaid2.MyMaid2
version: 0.0.1
description: General Plugin Version 2
database: true
author: mine_book000
commands:
   afk:
      description: AFK(Away From Keyboard)モードをオン・オフにします。
      usage: "/<command>: AFK(Away From Keyboard)モードをオン・オフにします。"
      permission: mymaid.afk
      permission-message: You do not have permission to perform this command.