name: MyMaid2
main: com.jaoafa.MyMaid2.MyMaid2
version: 0.0.1
description: General Plugin Version 2
database: true
author: mine_book000
softdepend: [PermissionsEx, LuckPerms, GeoipAPI, dynmap]
commands:
   afk:
      description: AFK(Away From Keyboard)モードをオン・オフにします。
      usage: "/afk: AFK(Away From Keyboard)モードをオン・オフにします。(トグル)"
      permission: mymaid.afk
      permission-message: You do not have permission to perform this command.
   dt:
      description: Dynmapのマーカー地点にテレポートします。
      usage: |-
             
             /dt [Player] <MarkerName...>: MarkerNameにテレポートします。Playerを指定した場合はそのPlayerをテレポートさせます。
             /dt near: あなたの近くのマーカーを表示します。
             /dt add <MarkerName> <MarkerType>: Markerを追加します。
             /dt del <MarkerName> <MarkerType>: Markerを削除します。
             /dt list: Markerリストを表示します。
             /dt list <Page>: 指定されたページのMarkerリストを表示します。
      permission: mymaid.dt
      permission-message: You do not have permission to perform this command.
   city:
      description: 市の範囲を登録したり削除したりできます。
      usage: |-
             
             /city addcorner: コーナーを追加
             /city addcorner <Name>: 既存のエリアにコーナーを追加
             /city undocorner: ひとつ前に追加したコーナーを削除
             /city clearcorner: コーナーを削除
             /city show: いまいる地点の情報を表示。(未完成)
             /city add <Name> <Color>: エリアの範囲を色と共に設定(Dynmapに表示)
             /city del <Name>: エリアの範囲を削除
             /city setcolor <Name> <Color>: エリアの色を変更
             /city editcorner <Name>: 指定されたエリアのコーナーエディタを使用してコーナーを編集
             /city setdesc <Name> <Description>: エリアの説明を設定
             /city show <Name>: エリアの情報を表示。
      permission: mymaid.city
      permission-message: You do not have permission to perform this command.
   cmdb:
      description: コマンドブロックを与えます。
      usage: |-
             
             /cmdb: メインハンドにコマンドブロックを設定します。すでに持っていたアイテムは別のスロットに移動するかドロップします。
             /cmdb <Player>: 指定したプレイヤーのメインハンドにコマンドブロックを設定します。すでに持っていたアイテムは別のスロットに移動するかドロップします。
      permission: mymaid.cmdb
      permission-message: You do not have permission to perform this command.
   home:
      description: ホームにテレポートします。
      usage: |-
             
             /home: デフォルトのホームにテレポートします。
             /home <Name>: Nameのホームにテレポートします。
      permission: mymaid.home
      permission-message: You do not have permission to perform this command.
   sethome:
      description: ホームを設定します。
      usage: |-
             
             /sethome: デフォルト(default)でホームを設定します。上書きはできないため、事前に削除する必要があります。
             /sethome <Name>: 指定した名前でホームを設定します。上書きはできないため、事前に削除する必要があります。
      permission: mymaid.sethome
      permission-message: You do not have permission to perform this command.
   delhome:
      description: ホームを削除します。
      usage: "/delhome <Name>: 指定された名前のホームを削除します。"
      permission: mymaid.delhome
      permission-message: You do not have permission to perform this command.
   g:
      description: ゲームモードを変更します。
      usage: |-
             
             /g: クリエイティブモードならスペクテイターモードに、スペクテイターモードならクリエイティブモードに、それ以外ならクリエイティブモードに変更します。
             /g <0-3>: 指定された数値に合うゲームモードに変更します。
             /g <0-3> <Player>: 指定したプレイヤーのゲームモードを指定された数値に合うゲームモードに変更します。
      permission: mymaid.g
      permission-message: You do not have permission to perform this command.
   dedrain:
      description: 雨を降らすかどうか設定します。
      usage: |-
             
             /dedrain: 現在の降水禁止設定を確認します。
             /dedrain <true/false>: 降水禁止設定を変更します。
      permission: mymaid.dedrain
      permission-message: You do not have permission to perform this command.
   wt:
      description: 他ワールドにテレポートできるようになります。
      usage: "/wt <WorldID/WorldName>: 指定されたWorldIDもしくはWorldNameのワールドのスポーン地点にテレポートします。"
      permission: mymaid.wt
      permission-message: You do not have permission to perform this command.